import "./globals.css";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import AuthProvider from "@/context/auth-context";

export const metadata = {
  title: "Rayhan",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const locale = useLocale();
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  if (params.locale !== locale) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AuthProvider> {children}</AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
